FROM maven:3-openjdk-17 AS builder

WORKDIR /app

COPY . /app

EXPOSE 8080

RUN mvn clean package


FROM openjdk:17-alpine

WORKDIR /app

COPY --from=builder /app/target/demo-0.0.1-SNAPSHOT.jar /app/demo.jar

CMD java $JAVA_OPTS -jar demo.jar
